---
- name: Ensure OpenCloud admin password is provided
  ansible.builtin.assert:
    that: OC_ADMIN_PASSWORD != ""
    fail_msg: "OC_ADMIN_PASSWORD is missing."

- name: get hdd gid
  getent:
    database: group
    key: hdd

- name: Create opencloud user
  include_role:
    name: utils
    tasks_from: install_user.yml
  vars:
    username: opencloud
    user_groups:
      - hdd

- name: get opencloud user info
  getent:
    database: passwd
    key: opencloud

- name: Create opencloud config directory
  file:
    path: "/docker/opencloud"
    state: directory
    owner: opencloud
    group: opencloud
    mode: '0775'
    recurse: yes

- name: "Generate OpenCloud Docker Compose file"
  include_role:
    name: utils
    tasks_from: install_docker_compose_raw.yml
  vars:
    container_name: opencloud
    host: nighthawk
    docker_compose_content: |
      networks:
        proxy:
          external: true

      services:
        opencloud:
          image: opencloudeu/opencloud:2
          container_name: opencloud
          user: "{{ getent_passwd['opencloud'][1] }}:{{ getent_passwd['opencloud'][2] }}"
          environment:
            OC_URL: "https://{{ OC_DOMAIN }}"
            IDM_ADMIN_PASSWORD: "{{ OC_ADMIN_PASSWORD }}"
            OC_INSECURE: "false"
            OC_LOG_PRETTY: "true"
            PROXY_TLS: "false"
            PROXY_ENABLE_BASIC_AUTH: "true"
          volumes:
            - {{ OC_DATA_DIR }}:/var/lib/opencloud
            - /docker/opencloud/etc-opencloud:/etc/opencloud
            - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
          networks:
            - proxy
            - default
          entrypoint:
            - /bin/sh
          command: ["-c", "opencloud init || true; opencloud server"]
          restart: unless-stopped
          group_add:
            - "{{ getent_group['hdd'][1] }}"
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.opencloud.rule=Host(`{{ OC_DOMAIN }}`)"
            - "traefik.http.routers.opencloud.entrypoints=websecure"
            - "traefik.http.routers.opencloud.tls=true"
            - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
