---

#
# Supported Vars:
#   - JELLYFIN_CONTAINER: Defaults to "jellyfin/jellyfin"
#   - JELLYFIN_MEDIA_DIR: Required.
#   - JELLYFIN_SERVER_HOST: Required. Eg: jellyfin.foo.com
#

- name: Install Nextcloud docker container
  include_role:
    name: supersaiyanmode.ansible_utils.install_docker_image
  vars:
    container_name: jellyfin
    container_image: "{{ JELLYFIN_CONTAINER }}"
    server_host: "{{ JELLYFIN_SERVER_HOST }}"
    main_port: 8096
    image_pull: true
    container_mounts:
      - /config
      - /cache
    custom_mounts:
      - "{{ JELLYFIN_MEDIA_DIR }}:/media"
    env:

