---
- name: Install Nextcloud docker container
  include_role:
    name: supersaiyanmode.ansible_utils.install_docker_image
  vars:
    container_name: jellyfin
    container_image: "jellyfin/jellyfin"
    main_port: 8096
    container_mounts:
      - /config
      - /cache
    custom_mounts:
      - /hdd/nextcloud/movies/files:/media
    env:
      temp: temp

