all:
  hosts:
    eagle.lan:
    tomcat.lan:
  vars:
    configure_hdd: false
    configure_gpio: false
    configure_http: false
    install_nextcloud: false
    install_pihole: false
    install_jellyfin: false
    install_tailscale: false

gpio_hosts:
  hosts:
    eagle.lan:
    tomcat.lan:
  vars:
    configure_gpio: true

http_hosts:
  hosts:
    eagle.lan:
  vars:
    configure_http: true

hdd_hosts:
  hosts:
    eagle.lan:
      hdd_mount_path: /hdd
      hdd_device: /dev/sda1
      hdd_fs_type: ntfs
  vars:
    configure_hdd: true

nextcloud_hosts:
  hosts:
    eagle.lan:
  vars:
    install_nextcloud: true
    nextcloud_db_password: "{{ lookup('env', 'NEXTCLOUD_DB_PASSWD') }}"
    nextcloud_admin_user: srivatsan
    nextcloud_admin_passwd: "{{ lookup('env', 'NEXTCLOUD_ADMIN_PASSWD') }}"

pihole_hosts:
  hosts:
    eagle.lan:
  vars:
    install_pihole: true
    pihole_env_vars:
      FTLCONF_dhcp_start: 192.168.86.40
      FTLCONF_dhcp_end: 192.168.86.250
      FTLCONF_dhcp_router: 192.168.86.1
      FTLCONF_dns_hosts: "192.168.86.2 pihole.eagle.com;192.168.86.2 nextcloud.eagle.com;192.168.86.2 jellyfin.eagle.com;192.168.86.2 wud.eagle.com;192.168.86.2 anton.eagle.com"
      FTLCONF_webserver_api_password: "{{ lookup('env', 'PI_HOLE_ADMIN_PASSWD') }}"

tailscale_hosts:
  hosts:
    eagle.lan:
  vars:
    install_tailscale: true
    tailscale_env_vars:
      TS_AUTHKEY: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
      TS_HOSTNAME: eagle.com
      TS_ROUTES: 192.168.86.0/24

