all:
  hosts:
    eagle:
    tomcat:
  vars:
    configure_hdd: false
    configure_gpio: false
    configure_http: false
    install_nextcloud: false
    install_pihole: false
    install_jellyfin: false
    install_tailscale: false
    install_github_runner: false
    install_qbittorrent: false
    install_forgejo: false
    install_semaphore: false

semaphore_hosts:
  hosts:
    eagle:
  vars:
    install_semaphore: "{{ lookup('env', 'INSTALL_SEMAPHORE') == 'true' }}"
    semaphore_db_password: "{{ lookup('env', 'SEMAPHORE_DB_PASSWD') }}"
    semaphore_domain: "http://semaphore.{{ lookup('env', 'MAIN_HOST_NAME')}}"
    semaphore_admin_name: srivatsan
    semaphore_admin_passwd: "{{ lookup('env', 'SEMAPHORE_ADMIN_PASSWD') }}"

jellyfin_hosts:
  hosts:
    eagle:
  vars:
    install_jellyfin: "{{ lookup('env', 'INSTALL_JELLYFIN') == 'true' }}"
    JELLYFIN_MEDIA_DIR: /hdd/nextcloud/movies/files
    JELLYFIN_SERVER_HOST: jellyfin.eagle.com

forgejo_hosts:
  hosts:
    eagle:
  vars:
    install_forgejo: "{{ lookup('env', 'INSTALL_FORGEJO') == 'true' }}"
    forgejo_db_password: "{{ lookup('env', 'FORGEJO_DB_PASSWD') }}"
    forgejo_db_user: forgejo
    forgejo_domain: "git.{{ lookup('env', 'MAIN_HOST_NAME')}}"

github_runner_hosts:
  hosts:
    eagle:
  vars:
    install_github_runner: "{{ lookup('env', 'INSTALL_GITHUB_RUNNER') == 'true' }}"
    repo: https://github.com/HomeWeave

gpio_hosts:
  hosts:
    eagle:
    tomcat:
  vars:
    configure_gpio: "{{ lookup('env', 'CONFIGURE_GPIO') == 'true' }}"

http_hosts:
  hosts:
    eagle:
  vars:
    configure_http: "{{ lookup('env', 'INSTALL_HTTP') == 'true' }}"

hdd_hosts:
  hosts:
    eagle:
      hdd_mount_path: /hdd
      hdd_device: /dev/sda1
      hdd_fs_type: ntfs
  vars:
    configure_hdd: "{{ lookup('env', 'CONFIGURE_BASIC') == 'true' }}"

nextcloud_hosts:
  hosts:
    eagle:
  vars:
    install_nextcloud: "{{ lookup('env', 'INSTALL_NEXTCLOUD') == 'true' }}"
    NEXTCLOUD_DB_PASSWORD: "{{ lookup('env', 'NEXTCLOUD_DB_PASSWD') }}"
    NEXTCLOUD_ADMIN_USER: srivatsan
    NEXTCLOUD_ADMIN_PASSWD: "{{ lookup('env', 'NEXTCLOUD_ADMIN_PASSWD') }}"
    NEXTCLOUD_DOMAIN: "nextcloud.{{ lookup('env', 'MAIN_HOST_NAME') }}"
    NEXTCLOUD_DATA_DIR: /hdd/nextcloud
    NEXTCLOUD_DATA_DIR_GROUP: hdd
    NEXTCLOUD_LOCAL_MOUNT_DIR: /home/srivatsan/nextcloud

pihole_hosts:
  hosts:
    eagle:
  vars:
    install_pihole: "{{ lookup('env', 'INSTALL_PIHOLE') == 'true' }}"
    DHCP_START: 192.168.86.40
    DHCP_END: 192.168.86.250
    DHCP_ROUTER: 192.168.86.1
    CUSTOM_DNS_NAMES: "192.168.86.2 pihole.eagle.com;192.168.86.2 nextcloud.eagle.com;192.168.86.2 jellyfin.eagle.com;192.168.86.2 wud.eagle.com;192.168.86.2 anton.eagle.com;192.168.86.2 qbittorrent.eagle.com;192.168.86.2 git.eagle.com;192.168.86.2 semaphore.eagle.com"

tailscale_hosts:
  hosts:
    eagle:
  vars:
    install_tailscale: "{{ lookup('env', 'INSTALL_TAILSCALE') == 'true' }}"
    tailscale_env_vars:
      TS_AUTHKEY: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
      TS_HOSTNAME: "{{ lookup('env', 'MAIN_HOST_NAME') }}"
      TS_ROUTES: "{{ lookup('env', 'SUBNET') }}"

qbittorrent_hosts:
  hosts:
    eagle:
  vars:
    install_qbittorrent: "{{ lookup('env', 'INSTALL_QBITTORRENT') == 'true' }}"
    QBITTORRENT_SERVER_HOST: "qbittorent.{{ lookup('env', 'MAIN_HOST_NAME') }}"
    QBITTORRENT_DOWNLOAD_DIR_GROUP: hdd
    QBITTORRENT_DOWNLOAD_DIR: /hdd/nextcloud/downloader/files

