all:
  hosts:
    eagle:
    tomcat:
    nighthawk:
  vars:
    configure_hdd: false
    configure_gpio: false
    configure_basic: false
    install_nextcloud: false
    install_pihole: false
    install_jellyfin: false
    install_tailscale: false
    install_github_runner: false
    install_qbittorrent: false
    install_forgejo: false
    install_semaphore: false
    install_traefik: false
    install_dockhand: false
    install_hawser: false

basic_hosts:
  hosts:
    nighthawk:
    eagle:
    falcon:
    raptor:
    tomcat:
  vars:
    configure_basic: "{{ lookup('env', 'CONFIGURE_BASIC') == 'true' }}"
    install_docker: "{{ lookup('env', 'CONFIGURE_DOCKER') == 'true' }}"
    install_traefik: "{{ lookup('env', 'INSTALL_TRAEFIK') == 'true' }}"
    traefik_dashboard_user: "{{ lookup('env', 'TRAEFIK_DASHBOARD_USER') }}"
    traefik_dashboard_passwd_hash: "{{ lookup('env', 'TRAEFIK_DASHBOARD_PASSWD_HASH') }}"

pihole_hosts:
  hosts:
    nighthawk:
  vars:
    install_pihole: "{{ lookup('env', 'INSTALL_PIHOLE') == 'true' }}"
    traefik_api_hosts:
      - eagle
      - nighthawk
      - raptor
      - falcon
      - tomcat

dockhand_hosts:
  hosts:
    nighthawk:
  vars:
    install_dockhand: "{{ lookup('env', 'INSTALL_DOCKHAND') == 'true' }}"

hawser_hosts:
  hosts:
    eagle:
    falcon:
    raptor:
    tomcat:
  vars:
    install_hawser: "{{ lookup('env', 'INSTALL_HAWSER') == 'true' }}"
    hawser_join_token: "{{ lookup('env', 'HAWSER_JOIN_TOKEN') }}"
    hawser_agent_id: "eagle-hawser"

semaphore_hosts:
  hosts:
    eagle:
  vars:
    install_semaphore: "{{ lookup('env', 'INSTALL_SEMAPHORE') == 'true' }}"
    semaphore_db_password: "{{ lookup('env', 'SEMAPHORE_DB_PASSWD') }}"
    SEMAPHORE_DOMAIN: "semaphore.{{ lookup('env', 'MAIN_HOST_NAME')}}"
    semaphore_admin_name: srivatsan
    semaphore_admin_passwd: "{{ lookup('env', 'SEMAPHORE_ADMIN_PASSWD') }}"

jellyfin_hosts:
  hosts:
    eagle:
  vars:
    install_jellyfin: "{{ lookup('env', 'INSTALL_JELLYFIN') == 'true' }}"
    JELLYFIN_MEDIA_DIR: /hdd/nextcloud/movies/files
    JELLYFIN_SERVER_HOST: "jellyfin.{{ lookup('env', 'MAIN_HOST_NAME') }}"

forgejo_hosts:
  hosts:
    nighthawk:
  vars:
    install_forgejo: "{{ lookup('env', 'INSTALL_FORGEJO') == 'true' }}"
    forgejo_db_password: "{{ lookup('env', 'FORGEJO_DB_PASSWD') }}"
    forgejo_db_user: forgejo
    forgejo_domain: "git.{{ lookup('env', 'MAIN_HOST_NAME')}}"
    forgejo_shared_secret1: "{{ lookup('env', 'FORGEJO_SHARED_SECRET1') }}"
    forgejo_shared_secret2: "{{ lookup('env', 'FORGEJO_SHARED_SECRET2') }}"
    forgejo_root_password: "{{ lookup('env', 'FORGEJO_ROOT_PASSWORD') }}"


github_runner_hosts:
  hosts:
    eagle:
  vars:
    install_github_runner: "{{ lookup('env', 'INSTALL_GITHUB_RUNNER') == 'true' }}"
    GITHUB_RUNNER_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    GITHUB_ORG: https://github.com/HomeWeave

gpio_hosts:
  hosts:
    eagle:
    tomcat:
  vars:
    configure_gpio: "{{ lookup('env', 'CONFIGURE_GPIO') == 'true' }}"

hdd_hosts:
  hosts:
    eagle:
      hdd_mount_path: /hdd
      hdd_device: /dev/sda1
      hdd_fs_type: ntfs
  vars:
    configure_hdd: "{{ lookup('env', 'CONFIGURE_BASIC') == 'true' }}"

nextcloud_hosts:
  hosts:
    eagle:
  vars:
    install_nextcloud: "{{ lookup('env', 'INSTALL_NEXTCLOUD') == 'true' }}"
    NEXTCLOUD_DB_PASSWORD: "{{ lookup('env', 'NEXTCLOUD_DB_PASSWD') }}"
    NEXTCLOUD_ADMIN_USER: srivatsan
    NEXTCLOUD_ADMIN_PASSWD: "{{ lookup('env', 'NEXTCLOUD_ADMIN_PASSWD') }}"
    NEXTCLOUD_DOMAIN: "nextcloud.{{ lookup('env', 'MAIN_HOST_NAME') }}"
    NEXTCLOUD_DATA_DIR: /hdd/nextcloud
    NEXTCLOUD_DATA_DIR_GROUP: hdd
    NEXTCLOUD_LOCAL_MOUNT_DIR: /home/srivatsan/nextcloud

tailscale_hosts:
  hosts:
    eagle:
  vars:
    install_tailscale: "{{ lookup('env', 'INSTALL_TAILSCALE') == 'true' }}"
    TAILSCALE_AUTHKEY: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') | default(TAILSCALE_AUTH_KEY) }}"
    TAILSCALE_HOSTNAME: eagle.com
    TAILSCALE_SUBNET: "192.168.86.0/24"
    TAILSCALE_EXIT_NODE: true

qbittorrent_hosts:
  hosts:
    eagle:
  vars:
    install_qbittorrent: "{{ lookup('env', 'INSTALL_QBITTORRENT') == 'true' }}"
    QBITTORRENT_SERVER_HOST: "qbittorent.{{ lookup('env', 'MAIN_HOST_NAME') }}"
    QBITTORRENT_DOWNLOAD_DIR_GROUP: hdd
    QBITTORRENT_DOWNLOAD_DIR: /hdd/nextcloud/downloader/files

