 - hosts: all
   remote_user: "{{ lookup('env', 'USER') }}"
   become: yes
   become_user: root
   become_method: sudo
   roles:
     - role: configure_hdd
       when:  configure_hdd

     - role: configure_gpio
       when:  configure_gpio

     - role: supersaiyanmode.ansible_utils.install_http
       when: configure_http

     - role: pihole
       when: install_pihole

     - role: nextcloud
       when: install_nextcloud

     - role: jellyfin
       when: install_jellyfin

     - role: tailscale
       when: install_tailscale

     - role: qbittorrent
       when: install_qbittorrent

     - role: github_actions_self_hosted
       when: install_github_runner

     - role: wud
       when: "lookup('env', 'INSTALL_WUD') == 'true'"

     - role: forgejo
       when: install_forgejo

     - role: semaphore
       when: install_semaphore
