 - hosts: all
   remote_user: srivatsan
   become: yes
   become_user: root
   become_method: sudo
   roles:
     - role: supersaiyanmode.ansible_utils.install_user
       username: hdd
       when: lookup('env', 'CONFIGURE_BASIC') == 'true'

     - role: supersaiyanmode.ansible_utils.configure_mounts
       mounts:
         - path: /hdd
           dev: /dev/sda1
           fstype: ntfs
           opts: defaults,rw,gid=hdd,umask=0007
           mounted: yes
       when: lookup('env', 'CONFIGURE_BASIC') == 'true'

     - role: supersaiyanmode.ansible_utils.install_user
       username: eagle
       become_method: sudo
       enable_sudo: true
       user_groups:
         - hdd
         - sudo
       when: lookup('env', 'CONFIGURE_BASIC') == 'true'

     - role: supersaiyanmode.ansible_utils.install_http
       when: lookup('env', 'INSTALL_HTTP') == 'true'

     - role: supersaiyanmode.ansible_utils.install_mysql
       databases:
         - nextcloud
       users:
         - name: nextcloud
           password: "{{ lookup('env', 'NEXTCLOUD_DB_PASSWD') }}"
           host: '172.17.%'
       permissions:
         - database: nextcloud
           user: nextcloud
           host: '172.17.%'
       when: lookup('env', 'INSTALL_MYSQL') == 'true'

     - role: pihole
       when: "lookup('env', 'INSTALL_PIHOLE') == 'true'"
     - role: nextcloud
       when: "lookup('env', 'INSTALL_NEXTCLOUD') == 'true'"
     - role: jellyfin
       when: "lookup('env', 'INSTALL_JELLYFIN') == 'true'"
     - role: github_actions_self_hosted
       repo: https://github.com/HomeWeave
       when: "lookup('env', 'INSTALL_GITHUB_RUNNER') == 'true'"
     - role: wud
       when: "lookup('env', 'INSTALL_WUD') == 'true'"
