---

- name: Install MySQL
  include_role:
    name: supersaiyanmode.ansible_utils.install_mysql
  vars:
     databases:
       - nextcloud
     users:
       - name: nextcloud
         password: "{{ nextcloud_db_password }}"
         host: '172.17.%'
     permissions:
       - database: nextcloud
         user: nextcloud
         host: '172.17.%'

- name: Get gid of hdd.
  shell:
    cmd: echo $(id -u hdd)
  register: hdd_gid

- name: Create /hdd/nextcloud directory
  file:
    path: /hdd/nextcloud
    state: directory
    owner: hdd
    group: hdd

- name: Create .ncdata
  copy:
    dest: /hdd/nextcloud/.ncdata
    content: "# Nextcloud data directory\n# Do not change this file"

- name: Install Nextcloud docker container
  include_role:
    name: supersaiyanmode.ansible_utils.install_docker_image
  vars:
    container_name: nextcloud
    container_image: "nextcloud:latest"
    container_ports: "10090:80"
    network_mode: "bridge"
    image_pull: true
    main_port: 10090
    container_mounts:
      - /var/www/html/config
      - /var/www/html/custom_apps
    custom_mounts:
      - /hdd/nextcloud:/data
    setup_commands:
      - cmd: "/bin/bash -c 'getent group hdd || groupadd hdd -g {{ hdd_gid.stdout }}'"
        user: root
      - cmd: "usermod -a -G hdd www-data"
        user: root
      - cmd: "mkdir -p /data"
        user: root
      - user: www-data
        cmd: >
          /bin/bash -c "(php occ status | grep installed | grep true) ||
          php occ maintenance:install
          --database mysql --database-host 172.17.0.1 --database-name nextcloud
          --database-user nextcloud
          --database-pass {{ nextcloud_db_password }}
          --admin-user {{ nextcloud_admin_user }}
          --admin-pass {{ nextcloud_admin_passwd }}"
      - user: www-data
        cmd: >
          php occ config:system:set trusted_domains 1
          --value "nextcloud.eagle.com"
      - user: www-data
        cmd: php occ config:system:set trusted_proxies 0 --value "172.17.0.0/24"
      - user: www-data
        cmd: php occ config:system:set datadirectory --value "/data"
      - user: www-data
        cmd: >
          php occ config:system:set overwrite.cli.url
          --value "http://nextcloud.eagle.com"
      - user: www-data
        cmd: php occ config:system:set filesystem_check_changes --value 1
      - user: www-data
        cmd: php occ upgrade
    env:
      NEXTCLOUD_INIT_HTACCESS: "true"

- name: Setup cron for Nextcloud
  ansible.builtin.cron:
    name: Nextcloud Cron
    minute: "*/5"
    job: docker exec -u www-data nextcloud php cron.php

- name: Install davfs2
  include_role:
    name: supersaiyanmode.ansible_utils.install_packages
  vars:
    packages:
      - davfs2

- name: Davfs secrets
  lineinfile:
    path: /etc/davfs2/secrets
    search_string: "{{ nextcloud_admin_user }}"
    line: "/home/srivatsan/nextcloud \
      {{ nextcloud_admin_user }} \
      {{ nextcloud_admin_passwd }}"
    mode: '0600'

- name: Create ~/nextcloud directory
  file:
    path: /home/srivatsan/nextcloud
    state: directory

- name: Mount nextcloud
  ansible.posix.mount:
    path: /home/srivatsan/nextcloud
    src: "http://localhost:10090/remote.php/dav/files/{{ nextcloud_admin_user }}"
    opts: user,rw,sync,auto
    fstype: davfs
    state: mounted
