---

- name: Get gid of hdd.
  shell:
    cmd: echo $(id -u hdd)
  register: hdd_gid

- name: Create /hdd/nextcloud directory
  file:
    path: /hdd/nextcloud
    state: directory
    owner: hdd
    group: hdd

- name: Create .ncdata
  copy:
    dest: /hdd/nextcloud/.ncdata
    content: "# Nextcloud data directory\n# Do not change this file"

- name: Install Nextcloud docker container
  include_role:
    name: supersaiyanmode.ansible_utils.install_docker_image
  vars:
    container_name: nextcloud
    container_image: "nextcloud:latest"
    container_ports: "10090:80"
    network_mode: "bridge"
    main_port: 10090
    container_mounts:
      - /var/www/html/config
      - /var/www/html/custom_apps
    custom_mounts:
      - /hdd/nextcloud:/data
    setup_commands:
      - cmd: "/bin/bash -c 'getent group hdd || groupadd hdd -g {{ hdd_gid.stdout }}'"
      - cmd: "usermod -a -G hdd www-data"
      - cmd: "mkdir -p /data"
      - user: www-data
        cmd: >
          /bin/bash -c "(php occ status | grep installed | grep true) ||
          php occ maintenance:install
          --database mysql --database-host 172.17.0.1 --database-name nextcloud
          --database-user nextcloud
          --database-pass {{ lookup('env', 'NEXTCLOUD_DB_PASSWD') }}
          --admin-user {{ lookup('env', 'NEXTCLOUD_ADMIN_USER') }}
          --admin-pass {{ lookup('env', 'NEXTCLOUD_ADMIN_PASSWD') }}"
      - user: www-data
        cmd: >
          php occ config:system:set trusted_domains 1
          --value "nextcloud.eagle.com"
      - user: www-data
        cmd: php occ config:system:set trusted_proxies 0 --value "172.17.0.0/24"
      - user: www-data
        cmd: php occ config:system:set datadirectory --value "/data"
      - user: www-data
        cmd: >
          php occ config:system:set overwrite.cli.url
          --value "http://nextcloud.eagle.com"
    env:
      NEXTCLOUD_INIT_HTACCESS: "true"

