---

- name: Static configurations
  set_fact:
    env_vars:
      TS_STATE_DIR: /tailscale-config
      TS_ACCEPT_DNS: 'true'

- name: Tailscale docker container
  include_role:
    name: supersaiyanmode.ansible_utils.install_docker_image
  vars:
    container_name: tailscale
    container_image: "tailscale/tailscale:latest"
    devices:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - NET_ADMIN
    container_mounts:
      - /tailscale-config
    env: "{{ tailscale_env_vars | combine(env_vars) }}"
