---

- name: Tailscale docker container
  include_role:
    name: supersaiyanmode.ansible_utils.install_docker_image
  vars:
    container_name: tailscale
    container_image: "tailscale/tailscale:latest"
    image_pull: true
    devices:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - NET_ADMIN
    container_mounts:
      - /tailscale-config
    env:
      TS_STATE_DIR: /tailscale-config
      TS_ACCEPT_DNS: 'true'
      TS_AUTHKEY: "{{ TAILSCALE_AUTHKEY }}"
      TS_HOSTNAME: "{{ TAILSCALE_HOSTNAME }}"
      TS_ROUTES: "{{ TAILSCALE_SUBNET }}"
      TS_EXTRA_ARGS: "{{ '--advertise-exit-node' if TAILSCALE_EXIT_NODE else omit }}"
